baseURL = "https://coindarw.github.io/blog/"
languageCode = "ja"
defaultContentLanguage = "ja"
title = "coindarw's page"
theme = "anubis"
[pagination]
paginate = 5

# disqusShortname = ""
# googleAnalytics = ""
disableComments = false
# [author]
# name = "coindarw"

[params]
toc = true
author = "coindarw"
description = "coindarwのページ"
dateFormat = "2006-01-02"
# paginationSinglePost = true
style = "auto"
readMore = false
# readNextPosts = 2
copyCodeButton = true
rssAsSocialIcon = true
mathjax = true
customCSS = ["css/custom.css"]


# Graphcomment support
graphcommentId = ""

# utteranc.es support
utterancesRepo = ""  # mandatory
utterancesTheme = "" # optional
utterancesIssue = "" # optional
utterancesLabel = "" # optional

# # Giscus support
# GiscusRepo = ""  # mandatory
# GiscusRepoId = ""  # mandatory
# GiscusCategory = "Announcements" # mandatory
# GiscusCategoryId = ""  # mandatory
# GiscusLazyLoad = false  # optional

# [[params.social]]
# id = "docs"
# url = "https://gohugo.io/documentation/"

[[params.social]]
id = "github"
url = "https://github.com/coindarw"

[menu]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
name = "Archive"
identifier = "archive"
url = "/posts/"
weight = 3

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true
